### ISSUE TITLE
get mouse postion are absen from Unandled Input Event

### ISSUE THREAD

**Issue by EnderGamerXPnew** [CraterCrash/godot-orchestrator#686]
### Description

in gdscript they he fonction didicated for get the position of the mouse witch can be apply in the Unandled Input Event fonction but when i tried in visual script the fonction are only evaible the Subview port instead, making error if whe tried to use this fonction out of this object

**Comment by Naros** [comment]
Hi @EnderGamerXPnew can you share a screenshot of what you're referring to?

**Comment by Naros** [comment]
I think we discussed this on Discord, the `get_position` depends on the type of `InputEvent` you want to work with.  You need to drag from the output pin for the `event` and cast the type to an `InputEventMouseButton` or `InputEventMouseMotion` type in order to get access to the `get_position()` function.
