### ISSUE TITLE
Make File List and Component Panels hideable

### ISSUE THREAD

**Issue by dschiller** [CraterCrash/godot-orchestrator#732]
### Description

In Godot's Script Editor the File List can be collapsed / hidden.

![Screenshot from 2024-08-12 22-32-08](https://github.com/user-attachments/assets/faa4d1a9-f547-41ed-8051-0fbeefa14a88)

It would be handy to be able to hide and unhide the Orchestrator File List and Component Panels.

### Implementation ideas

Add Buttons to hide and show the File List and Component Panels.

![Screenshot from 2024-08-12 22-36-25](https://github.com/user-attachments/assets/e2758e18-23a6-44c1-a110-fee54440b801)

**Comment by Naros** [comment]
Hi @dschiller we chose not to add any extra real-estate buttons in favor of only having these on the `File` menu, see:

![Uploading image.png…]()

**Comment by dschiller** [comment]
That is the solution! Perfect! No extra buttons needed of course.

**Comment by ShalokShalom** [comment]
I was looking for this functionality as well, and think making it possible to just completely drag the border to the complete left, to deactivate it, would be perfect. 

How about that? 😸

**Comment by Naros** [comment]
> I was looking for this functionality as well, and think making it possible to just completely drag the border to the complete left, to deactivate it, would be perfect.

We should ideally focus on making sure that Orchestrator adheres to the same common behaviors for other parts of the editor and in no way does the **Script** tab or others work this way, so I don't think we should either.

There are really two solutions here that I think make sense:

* We leave it as-is until keybindings can be customized, which means fixing the Godot upstream issue. To me, this should be the ideal way to address this since it provides a wide array of benefits, including customizing hotkeys for other actions that you may perform in the graph canvas, which can't be customized at this time.
* We introduce `<` and `>` icon buttons in a bottom bar like the **Script** tab. My concern with this approach is questionable real-estate usage. Does Orchestrator have sufficient detail to justify the loss of canvas space for that, particularly for users who may have smaller screens or those using 200% editor UI scaling.

**Comment by dschiller** [comment]
i also believe this kind of behavior should be implemented by Godot, not the Orchestrator as the Window "Docking" System comes from Godot.

**Comment by ShalokShalom** [comment]
> > I was looking for this functionality as well, and think making it possible to just completely drag the border to the complete left, to deactivate it, would be perfect.
> 
> We should ideally focus on making sure that Orchestrator adheres to the same common behaviors for other parts of the editor and in no way does the **Script** tab or others work this way, so I don't think we should either.
> 
> There are really two solutions here that I think make sense:
> 
> * We leave it as-is until keybindings can be customized, which means fixing the Godot upstream issue. To me, this should be the ideal way to address this since it provides a wide array of benefits, including customizing hotkeys for other actions that you may perform in the graph canvas, which can't be customized at this time.
> * We introduce `<` and `>` icon buttons in a bottom bar like the **Script** tab. My concern with this approach is questionable real-estate usage. Does Orchestrator have sufficient detail to justify the loss of canvas space for that, particularly for users who may have smaller screens or those using 200% editor UI scaling.

I use a 175% 2.8K screen with 14 inch and I find that feature pretty essential.

Particularly since screen estate is often called out for a visual programming language.

I like the idea, to adhere to Godot standards, so I think the button is fine.

**Comment by Naros** [comment]
So in an ideal world, the `ScriptEditor` APIs would be exposed in a way that GDExtension plug-ins could use them, and if that were the case, then a lot of what you see in the **Script** tab would be inherited by Orchestrator; however, since that API isn't publicly exposed, we are limited to creating a full editor "main screen" implementation that forces us to implement some of the Godot editor behavior manually. Some examples of that include:

* Floating window logic
* Script file listing
* Collapsing left/right panels

Whenever the `ScriptEditor` API is finally exposed, we can look at moving Orchestrator there. However, that will be a relatively invasive change when and if Godot's devs ever fully expose that API.

So coming back to @dschiller comment:
> i also believe this kind of behavior should be implemented by Godot, not the Orchestrator as the Window "Docking" System comes from Godot.

I concur, that would be nice, but given the above, we are somewhat forced to implement some of this on our own until our UI can be embedded as a `ScriptEditor` implementation.

> (I dont understand what you mean with < and > button. I was refering to the fullscreen button in the script view.)

The "Distraction Free Mode" toggle at the very most top-right of the main view, that's provided directly by Godot. The button to switch to floating view, that's provided by Orchestrator since that part of the main view is part of our "main screen" implementation.

The `<` and `>` buttons I am referring to, if you go to the **Script** tab and open any text file or script, you'll notice that just below the text editor, there is a line that looks like this:

If you press the `<` icon, that toggles the script/filename panel. I'm suggesting we introduce a similar bar at the bottom of the graph canvas that works similarly.
